name: flutter_oss_licenses
description: A tool to generate detail and better OSS license list using pubspec.yaml/lock files.
version: 2.0.1
homepage: https://github.com/espresso3389/flutter_oss_licenses/tree/master/packages/flutter_oss_licenses
repository: https://github.com/espresso3389/flutter_oss_licenses
publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"

executables:
  generate:

dependencies:
  path: ^1.9.0
  meta: ^1.12.0
  yaml: ^3.1.2
  dart_pubspec_licenses: # ^2.0.2
    path: ../dart_pubspec_licenses
    # git:
    #   url: https://github.com/intaekim-gea/flutter_oss_licenses.git
    #   ref: update-to-remove-unneeded
    #   path: packages/dart_pubspec_licenses
  args: ^2.4.2

dev_dependencies:
  flutter_lints: ^4.0.0
