name: dart_pubspec_licenses
description: A library to make it easy to extract OSS license information from Dart packages using pubspec.yaml
version: 2.0.2
homepage: https://github.com/espresso3389/flutter_oss_licenses/tree/master/packages/dart_pubspec_licenses
repository: https://github.com/espresso3389/flutter_oss_licenses

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  yaml: ^3.1.0
  path: ^1.8.0
  json_annotation: ^4.5.0
  collection: ^1.18.0  
  pana: ^0.22.2

dev_dependencies:
  lints: ^3.0.0
  json_serializable: ^6.2.0
  build_runner: ^2.1.11
